const globalStyles = {
  colors: {
    primary: '#007AFF',
    secondary: '#FF3B30',
    tertiary: '#34C759',
    quaternary: '#FF9500',
    background: '#F5F5F5',
    text: '#333333',
    error: '#FF0000',
    success: '#008000',
    disabled: '#A6A6A6',
    lightGray: '#CCCCCC',
    darkGray: '#666666',
    white: '#FFFFFF',
    black: '#000000',
    transparent: 'transparent',
  },
  fontSizes: {
    tiny: 10,
    small: 12,
    medium: 16,
    large: 20,
    extraLarge: 24,
    huge: 32,
  },
  fontWeights: {
    light: '200',
    regular: '400',
    medium: '500',
    bold: '700',
    heavy: '900',
  },
  spacing: {
    tiny: 4,
    small: 8,
    medium: 16,
    large: 24,
    extraLarge: 32,
    huge: 48,
  },
  borderRadius: {
    small: 4,
    medium: 8,
    large: 16,
    round: 100,
  },
  boxShadow: {
    tiny: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.22,
      shadowRadius: 2.22,
      elevation: 3,
    },
    small: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 3,
      },
      shadowOpacity: 0.27,
      shadowRadius: 4.65,
      elevation: 6,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 5,
      },
      shadowOpacity: 0.36,
      shadowRadius: 6.68,
      elevation: 11,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 10,
      },
      shadowOpacity: 0.25,
      shadowRadius: 20,
      elevation: 24,
    },
  },
  buttonStyles: {
    primary: {
      backgroundColor: '#007AFF',
      borderRadius: 8,
      paddingVertical: 16,
      paddingHorizontal: 32,
    },
    secondary: {
      backgroundColor: '#FF3B30',
      borderRadius: 8,
      paddingVertical: 16,
      paddingHorizontal: 32,
    },
    tertiary: {
      backgroundColor: '#34C759',
      borderRadius: 8,
      paddingVertical: 16,
      paddingHorizontal: 32,
    },
    quaternary: {
      backgroundColor: '#FF9500',
      borderRadius: 8,
      paddingVertical: 16,
      paddingHorizontal: 32,
    },
    transparent: {
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: '#007AFF',
      borderRadius: 8,
      paddingVertical: 16,
      paddingHorizontal: 32,
    },
  },
};
