const globalStyles = {
  colors: {
    primary: '#007AFF',
    primaryLight: '#00B0FF',
    primaryDark: '#0066CC',
    secondary: '#FF3B30',
    secondaryLight: '#FF5A4D',
    secondaryDark: '#C60000',
    background: '#F5F5F5',
    backgroundLight: '#FFFFFF',
    backgroundDark: '#E0E0E0',
    text: '#333333',
    textLight: '#FFFFFF',
    textDark: '#000000',
    error: '#FF0000',
    success: '#008000',
    warning: '#FFA500',
    info: '#00BFFF',
  },
  fontSizes: {
    tiny: 10,
    small: 12,
    medium: 16,
    large: 20,
    extraLarge: 24,
    huge: 28,
  },
  fontWeights: {
    thin: '100',
    light: '200',
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
  },
  spacing: {
    tiny: 4,
    small: 8,
    medium: 16,
    large: 24,
    extraLarge: 32,
    huge: 40,
  },
  borderRadius: {
    none: 0,
    tiny: 2,
    small: 4,
    medium: 8,
    large: 16,
    pill: 9999,
  },
  boxShadow: {
    none: {},
    small: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.22,
      shadowRadius: 2.22,
      elevation: 3,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 3,
      },
      shadowOpacity: 0.27,
      shadowRadius: 4.65,
      elevation: 6,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 5,
      },
      shadowOpacity: 0.36,
      shadowRadius: 6.68,
      elevation: 11,
    },
    extraLarge: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowOpacity: 0.37,
      shadowRadius: 7.49,
      elevation: 12,
    },
  },
  buttonStyles: {
    primary: {
      backgroundColor: '#007AFF',
      backgroundColorLight: '#00B0FF',
      backgroundColorDark: '#0066CC',
      borderRadius: 8,
      paddingVertical: 16,
      paddingHorizontal: 32,
    },
    secondary: {
      backgroundColor: '#FF3B30',
      backgroundColorLight: '#FF5A4D',
      backgroundColorDark: '#C60000',
      borderRadius: 8,
      paddingVertical: 16,
      paddingHorizontal: 32,
    },
    tertiary: {
      backgroundColor: '#FFFFFF',
      backgroundColorLight: '#F5F5F5',
      backgroundColorDark: '#CCCCCC',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#CCCCCC',
      paddingVertical: 16,
      paddingHorizontal: 32,
    },
  },
};
