export const paddingMap = new Map<
  string,
  {padding?: number} | {paddingHorizontal?: number} | {paddingVertical?: number}
>([
  ['p-0', {padding: 0}],
  ['p-x-0', {paddingHorizontal: 0}],
  ['p-y-0', {paddingVertical: 0}],
  ['p-px', {padding: 1}],
  ['p-x-px', {paddingHorizontal: 1}],
  ['p-y-px', {paddingVertical: 1}],
  ['p-0.5', {padding: 2}],
  ['p-x-0.5', {paddingHorizontal: 2}],
  ['p-y-0.5', {paddingVertical: 2}],
  ['p-1', {padding: 4}],
  ['p-x-1', {paddingHorizontal: 4}],
  ['p-y-1', {paddingVertical: 4}],
  ['p-1.5', {padding: 6}],
  ['p-x-1.5', {paddingHorizontal: 6}],
  ['p-y-1.5', {paddingVertical: 6}],
  ['p-2', {padding: 8}],
  ['p-x-2', {paddingHorizontal: 8}],
  ['p-y-2', {paddingVertical: 8}],
  ['p-2.5', {padding: 10}],
  ['p-x-2.5', {paddingHorizontal: 10}],
  ['p-y-2.5', {paddingVertical: 10}],
  ['p-3', {padding: 12}],
  ['p-x-3', {paddingHorizontal: 12}],
  ['p-y-3', {paddingVertical: 12}],
  ['p-3.5', {padding: 14}],
  ['p-x-3.5', {paddingHorizontal: 14}],
  ['p-y-3.5', {paddingVertical: 14}],
  ['p-4', {padding: 16}],
  ['p-x-4', {paddingHorizontal: 16}],
  ['p-y-4', {paddingVertical: 16}],
  ['p-5', {padding: 20}],
  ['p-x-5', {paddingHorizontal: 20}],
  ['p-y-5', {paddingVertical: 20}],
  ['p-6', {padding: 24}],
  ['p-x-6', {paddingHorizontal: 24}],
  ['p-y-6', {paddingVertical: 24}],
  ['p-7', {padding: 28}],
  ['p-x-7', {paddingHorizontal: 28}],
  ['p-y-7', {paddingVertical: 28}],
  ['p-8', {padding: 32}],
  ['p-x-8', {paddingHorizontal: 32}],
  ['p-y-8', {paddingVertical: 32}],
]);

export const marginMap = new Map<
  string,
  {margin?: number} | {marginHorizontal?: number} | {marginVertical?: number}
>([
  ['m-0', {margin: 0}],
  ['m-x-0', {marginHorizontal: 0}],
  ['m-y-0', {marginVertical: 0}],
  ['m-px', {margin: 1}],
  ['m-x-px', {marginHorizontal: 1}],
  ['m-y-px', {marginVertical: 1}],
  ['m-0.5', {margin: 2}],
  ['m-x-0.5', {marginHorizontal: 2}],
  ['m-y-0.5', {marginVertical: 2}],
  ['m-1', {margin: 4}],
  ['m-x-1', {marginHorizontal: 4}],
  ['m-y-1', {marginVertical: 4}],
  ['m-1.5', {margin: 6}],
  ['m-x-1.5', {marginHorizontal: 6}],
  ['m-y-1.5', {marginVertical: 6}],
  ['m-2', {margin: 8}],
  ['m-x-2', {marginHorizontal: 8}],
  ['m-y-2', {marginVertical: 8}],
  ['m-2.5', {margin: 10}],
  ['m-x-2.5', {marginHorizontal: 10}],
  ['m-y-2.5', {marginVertical: 10}],
  ['m-3', {margin: 12}],
  ['m-x-3', {marginHorizontal: 12}],
  ['m-y-3', {marginVertical: 12}],
  ['m-3.5', {margin: 14}],
  ['m-x-3.5', {marginHorizontal: 14}],
  ['m-y-3.5', {marginVertical: 14}],
  ['m-4', {margin: 16}],
  ['m-x-4', {marginHorizontal: 16}],
  ['m-y-4', {marginVertical: 16}],
  ['m-5', {margin: 20}],
  ['m-x-5', {marginHorizontal: 20}],
  ['m-y-5', {marginVertical: 20}],
  ['m-6', {margin: 24}],
  ['m-x-6', {marginHorizontal: 24}],
  ['m-y-6', {marginVertical: 24}],
  ['m-7', {margin: 28}],
  ['m-x-7', {marginHorizontal: 28}],
  ['m-y-7', {marginVertical: 28}],
  ['m-8', {margin: 32}],
  ['m-x-8', {marginHorizontal: 32}],
  ['m-y-8', {marginVertical: 32}],
]);

export const gapMap = new Map<
  string,
  {gap?: number} | {columnGap?: number} | {rowGap?: number}
>([
  ['gap-0', {gap: 0}],
  ['gap-x-0', {columnGap: 0}],
  ['gap-y-0', {rowGap: 0}],
  ['gap-px', {gap: 1}],
  ['gap-x-px', {columnGap: 1}],
  ['gap-y-px', {rowGap: 1}],
  ['gap-0.5', {gap: 2}],
  ['gap-x-0.5', {columnGap: 2}],
  ['gap-y-0.5', {rowGap: 2}],
  ['gap-1', {gap: 4}],
  ['gap-x-1', {columnGap: 4}],
  ['gap-y-1', {rowGap: 4}],
  ['gap-1.5', {gap: 6}],
  ['gap-x-1.5', {columnGap: 6}],
  ['gap-y-1.5', {rowGap: 6}],
  ['gap-2', {gap: 8}],
  ['gap-x-2', {columnGap: 8}],
  ['gap-y-2', {rowGap: 8}],
  ['gap-2.5', {gap: 10}],
  ['gap-x-2.5', {columnGap: 10}],
  ['gap-y-2.5', {rowGap: 10}],
  ['gap-3', {gap: 12}],
  ['gap-x-3', {columnGap: 12}],
  ['gap-y-3', {rowGap: 12}],
  ['gap-3.5', {gap: 14}],
  ['gap-x-3.5', {columnGap: 14}],
  ['gap-y-3.5', {rowGap: 14}],
  ['gap-4', {gap: 16}],
  ['gap-x-4', {columnGap: 16}],
  ['gap-y-4', {rowGap: 16}],
  ['gap-5', {gap: 20}],
  ['gap-x-5', {columnGap: 20}],
  ['gap-y-5', {rowGap: 20}],
  ['gap-6', {gap: 24}],
  ['gap-x-6', {columnGap: 24}],
  ['gap-y-6', {rowGap: 24}],
  ['gap-7', {gap: 28}],
  ['gap-x-7', {columnGap: 28}],
  ['gap-y-7', {rowGap: 28}],
  ['gap-8', {gap: 32}],
  ['gap-x-8', {columnGap: 32}],
  ['gap-y-8', {rowGap: 32}],
]);
